#!/usr/bin/env node
// Build the client browser bundle for @wjj-8283/dsh-web-fetch-fakeip.
//
// The DSH web shell serves a plugin's browser half from the file its package.json
// `exports["./client"]` resolves to, and expects it to be a classic script calling
// `window.__ModuleLoader__.load({ id, factory })`. This script wraps
// ./src/client.js into exactly that contract and writes ./lib/client.js.
//
// Zero dependencies: the source is plain CJS that `require('react')`, which the
// shell's module loader supplies, so there is nothing to bundle.
//
//   node build.mjs            # one build
//   node build.mjs --watch    # rebuild on every change under ./src (HMR)
//   node build.mjs --check    # fail if lib/client.js is stale (used in CI)
import { readFileSync, writeFileSync, watchFile, watch } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const srcDir = join(root, 'src')
const srcFile = join(srcDir, 'client.js')
const outFile = join(root, 'lib', 'client.js')
const id = pkg.name
const isWatch = process.argv.includes('--watch')
const isCheck = process.argv.includes('--check')

function renderBundle() {
  const body = readFileSync(srcFile, 'utf8')
  return (
    `// ${id} — built by build.mjs from src/client.js; do not edit this file.\n` +
    `window.__ModuleLoader__.load({\n` +
    `  id: ${JSON.stringify(id)},\n` +
    `  factory: (require) => {\n` +
    `    var module = { exports: {} };\n` +
    `    var exports = module.exports;\n` +
    `\n${body}\n` +
    `    return module.exports;\n` +
    `  },\n` +
    `})\n`
  )
}

// --check: verify lib/client.js matches what a build would write, without touching
// the file. An npm package ships lib/ prebuilt, so it must never drift from src.
if (isCheck) {
  const expected = renderBundle()
  const current = readFileSync(outFile, 'utf8')
  if (current === expected) {
    console.log(`[check] lib/client.js is in sync (${id}, ${current.length} bytes)`)
    process.exit(0)
  }
  console.error(`[check] lib/client.js is STALE — run \`node build.mjs\` and commit the result (${id})`)
  process.exit(1)
}

function build(label) {
  const bundle = renderBundle()
  writeFileSync(outFile, bundle)
  console.log(`[build] ${label ?? 'ok'} -> lib/client.js (${id}, ${bundle.length} bytes)`)
}

// HMR is poll-based: it needs the bundle file to be (re)written with a new rev.
// writeFileSync guarantees a new mtime and content hash each build.
build('initial')

if (!isWatch) process.exit(0)

console.log(`[build] watching ${srcDir} for changes (Ctrl-C to stop)`)
try {
  const w = watch(srcDir, { recursive: true }, (_ev, filename) => scheduleRebuild(filename ?? 'src'))
  w.on('error', (err) => console.error('[build] recursive watch error:', err))
} catch {
  watchFile(srcFile, { interval: 200 }, () => scheduleRebuild('client.js'))
}

let timer
function scheduleRebuild(trigger) {
  clearTimeout(timer)
  timer = setTimeout(() => {
    try {
      build(`changed (${trigger})`)
    } catch (err) {
      console.error('[build] rebuild failed:', err)
    }
  }, 60)
}
