// @wjj-8283/dsh-web-fetch-fakeip — built by build.mjs from src/client.js; do not edit this file.
window.__ModuleLoader__.load({
  id: "@wjj-8283/dsh-web-fetch-fakeip",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

// @wjj-8283/dsh-web-fetch-fakeip — browser half SOURCE (editable).
//
// 一个「设置」页：开关 + fake-ip 地址段列表。写入走框架的 `ctx.configForms`
// 命名空间表单，因此改动会落到当前 profile 的 Cordis patch（cordis.patch.yml），
// 与手工编辑那个文件是同一份事实来源，服务端 entry 会随之重新 apply。
//
// 页面用 `settings.section` 插槽注册成设置导航里的一项（dsh 0.1.7 起，
// 插件自有设置界面的座位就是这个插槽；`slots.inject` 保证只在该插槽存在时注册）。
//
// 本文件是普通 CJS，由 ./build.mjs 包成
// `window.__ModuleLoader__.load({ id, factory })` 产物写到 ./lib/client.js。
// 在该产物里 `require` 是 shell 的模块加载器，react 由 shell 提供，不打进包里。
const react = require('react')

/** profile entry id，同时也是 settings 命名空间。 */
const ENTRY_ID = 'web-fetch-fakeip'
/** 设置导航里这一项的 id。 */
const SECTION_ID = 'web-fetch-fakeip'
/** 导航顺序（比内置项靠后，避免插到它们中间）。 */
const SECTION_ORDER = 60

/** 需要的浏览器侧服务：插槽注册、语言、以及设置表单。 */
const inject = ['slots', 'locale', 'configForms']

const zh = {
  nav: 'fake-ip 直连修复',
  title: 'web_fetch 与 fake-ip',
  intro:
    'Clash / mihomo 以 TUN + fake-ip 运行时，内置 web_fetch 会把 fake-ip 地址判为非公网地址而拒绝。这里放行的就是那几段。',
  enabled: '启用（放行 fake-ip 段）',
  enabledHint: '关闭后本插件不接管任何校验，web_fetch 恢复 dsh 原本的行为。',
  ranges: 'fake-ip 地址段（每行一个 CIDR）',
  rangesHint: '默认 198.18.0.0/15、fdfe:dcba:9876::/64、2001:2::/48。只有你的 Clash 用了非标准 fake-ip-range 时才需要改。',
  save: '保存',
  reset: '恢复默认',
  saved: '已保存',
  saveFail: '保存失败',
  resetDone: '已恢复默认段',
  badRange: '不是合法 CIDR：',
  loading: '正在读取…',
  unavailable: '当前连接下不可编辑（设置未托管在本机或处于只读模式）。',
  readonly: '当前 profile 不接受写入。',
  effective: '当前生效',
  off: '未启用',
}

const en = {
  nav: 'fake-ip fix',
  title: 'web_fetch and fake-ip',
  intro:
    'Under Clash / mihomo TUN mode with fake-ip, the built-in web_fetch rejects fake-ip addresses as non-public. These are the ranges this plugin lets through.',
  enabled: 'Enabled (let fake-ip ranges through)',
  enabledHint: 'When off, the plugin stops patching anything and web_fetch behaves as dsh ships it.',
  ranges: 'fake-ip ranges (one CIDR per line)',
  rangesHint: 'Defaults to 198.18.0.0/15, fdfe:dcba:9876::/64, 2001:2::/48. Change it only if your Clash uses a non-standard fake-ip-range.',
  save: 'Save',
  reset: 'Reset to defaults',
  saved: 'Saved',
  saveFail: 'Save failed',
  resetDone: 'Restored the default ranges',
  badRange: 'Not a valid CIDR: ',
  loading: 'Loading…',
  unavailable: 'Not editable on this connection (settings are not hosted locally, or read-only).',
  readonly: 'This profile does not accept writes.',
  effective: 'In effect',
  off: 'disabled',
}

/** 当前界面语言：优先问 locale 服务，退回 <html lang>，再退回 zh。 */
function activeLang(locale) {
  try {
    const fromService =
      (typeof locale?.get === 'function' ? locale.get('locale') : undefined) ??
      (typeof locale?.get === 'function' ? locale.get('lang') : undefined) ??
      locale?.snapshot?.()?.locale ??
      locale?.snapshot?.()?.lang
    if (typeof fromService === 'string' && fromService) return fromService.startsWith('en') ? 'en' : 'zh'
  } catch {
    /* 服务形态不认识就往下退 */
  }
  try {
    const attr = typeof document !== 'undefined' ? document.documentElement.getAttribute('lang') : null
    if (typeof attr === 'string' && attr) return attr.startsWith('en') ? 'en' : 'zh'
  } catch {
    /* 非浏览器环境 */
  }
  return 'zh'
}

/** 一句话：校验用户输入的 CIDR 是否合法（含前缀长度范围）。 */
function cidrProblem(text) {
  const slash = text.lastIndexOf('/')
  if (slash <= 0) return true
  const address = text.slice(0, slash)
  const bits = Number(text.slice(slash + 1))
  const isV4 = /^\d{1,3}(\.\d{1,3}){3}$/.test(address)
  const isV6 = /^[0-9a-fA-F:]+$/.test(address) && address.includes(':')
  if (!isV4 && !isV6) return true
  if (isV4) {
    if (!address.split('.').every((part) => Number(part) <= 255)) return true
    return !Number.isInteger(bits) || bits < 0 || bits > 32
  }
  return !Number.isInteger(bits) || bits < 0 || bits > 128
}

const styles = {
  page: { display: 'flex', flexDirection: 'column', gap: '18px', maxWidth: '640px', padding: '4px 0' },
  title: { margin: '0', fontSize: '15px', fontWeight: 600 },
  intro: { margin: '0', fontSize: '13px', lineHeight: '20px', opacity: 0.75 },
  field: { display: 'flex', flexDirection: 'column', gap: '6px' },
  label: { fontSize: '13px', fontWeight: 500 },
  hint: { fontSize: '12px', lineHeight: '18px', opacity: 0.65 },
  checkboxRow: { display: 'flex', alignItems: 'flex-start', gap: '8px' },
  textarea: {
    boxSizing: 'border-box',
    width: '100%',
    minHeight: '96px',
    padding: '8px 10px',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    lineHeight: '20px',
    color: 'inherit',
    background: 'transparent',
    border: '1px solid currentColor',
    borderRadius: '6px',
    opacity: 0.9,
    resize: 'vertical',
  },
  actions: { display: 'flex', alignItems: 'center', gap: '10px' },
  button: {
    padding: '5px 12px',
    fontSize: '13px',
    color: 'inherit',
    background: 'transparent',
    border: '1px solid currentColor',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  status: { fontSize: '12px', opacity: 0.75 },
  mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: '12px', opacity: 0.8 },
}

/**
 * 构建设置页组件。服务通过闭包注入，保持本文件不依赖 cordis 的客户端 API 形状。
 * @param forms - `ctx.configForms`
 * @param locale - `ctx.locale`（可为 undefined）
 * @returns 设置页的 React 组件。
 */
function createPage(forms, locale) {
  const t = (key) => (activeLang(locale) === 'en' ? en : zh)[key]

  return function FakeIpSettingsPage() {
    const form = react.useMemo(() => forms.get(ENTRY_ID), [])
    const snapshot = react.useSyncExternalStore(
      (listener) => form.subscribe(listener),
      () => form.getSnapshot(),
    )
    const [draft, setDraft] = react.useState(null)
    const [status, setStatus] = react.useState('')

    const section = snapshot.value ?? {}
    const enabled = section.enabled !== false
    const ranges = Array.isArray(section.fakeIpRanges) ? section.fakeIpRanges : []
    const text = draft === null ? ranges.join('\n') : draft
    const editable = snapshot.status === 'ready' && snapshot.writable === true

    const applyEnabled = async (next) => {
      setStatus('')
      let accepted = false
      try {
        accepted = await form.set('enabled', next)
      } catch {
        accepted = false
      }
      if (!accepted) setStatus(t('saveFail'))
    }

    const applyRanges = async (next) => {
      let accepted = false
      try {
        accepted = await form.set('fakeIpRanges', next)
      } catch {
        accepted = false
      }
      if (!accepted) setStatus(t('saveFail'))
      return accepted
    }

    const save = async () => {
      const lines = text
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line !== '')
      const bad = lines.find((line) => cidrProblem(line))
      if (bad !== undefined) {
        setStatus(t('badRange') + bad)
        return
      }
      if (lines.length === 0) {
        setStatus(t('badRange') + '(empty)')
        return
      }
      setStatus('')
      if (await applyRanges(lines)) {
        setDraft(null)
        setStatus(t('saved'))
      }
    }

    const reset = async () => {
      setStatus('')
      let accepted = false
      try {
        accepted = await form.unset('fakeIpRanges')
      } catch {
        accepted = false
      }
      if (!accepted) {
        setStatus(t('saveFail'))
        return
      }
      setDraft(null)
      setStatus(t('resetDone'))
    }

    if (snapshot.status === 'loading') {
      return react.createElement('div', { style: styles.page }, react.createElement('p', { style: styles.intro }, t('loading')))
    }

    return react.createElement(
      'div',
      { style: styles.page },
      react.createElement('h3', { style: styles.title }, t('title')),
      react.createElement('p', { style: styles.intro }, t('intro')),

      react.createElement(
        'div',
        { style: styles.checkboxRow },
        react.createElement('input', {
          type: 'checkbox',
          id: 'web-fetch-fakeip-enabled',
          checked: enabled,
          disabled: !editable,
          onChange: (event) => void applyEnabled(event.currentTarget.checked),
        }),
        react.createElement(
          'div',
          { style: styles.field },
          react.createElement('label', { htmlFor: 'web-fetch-fakeip-enabled', style: styles.label }, t('enabled')),
          react.createElement('span', { style: styles.hint }, t('enabledHint')),
        ),
      ),

      react.createElement(
        'div',
        { style: styles.field },
        react.createElement('span', { style: styles.label }, t('ranges')),
        react.createElement('textarea', {
          style: styles.textarea,
          value: text,
          disabled: !editable,
          spellCheck: false,
          onChange: (event) => setDraft(event.currentTarget.value),
        }),
        react.createElement('span', { style: styles.hint }, t('rangesHint')),
      ),

      react.createElement(
        'div',
        { style: styles.actions },
        react.createElement('button', { type: 'button', style: styles.button, disabled: !editable, onClick: () => void save() }, t('save')),
        react.createElement('button', { type: 'button', style: styles.button, disabled: !editable, onClick: () => void reset() }, t('reset')),
        status !== '' ? react.createElement('span', { style: styles.status }, status) : null,
      ),

      react.createElement(
        'div',
        { style: styles.status },
        `${t('effective')}: ${enabled ? ranges.join(', ') || '(default)' : t('off')}`,
      ),

      snapshot.status === 'unavailable'
        ? react.createElement('p', { style: styles.hint }, t('unavailable'))
        : snapshot.writable !== true
          ? react.createElement('p', { style: styles.hint }, t('readonly'))
          : null,
    )
  }
}

function apply(ctx) {
  const slots = ctx.get ? ctx.get('slots') : ctx.slots
  const locale = ctx.get ? ctx.get('locale') : ctx.locale
  const forms = ctx.get ? ctx.get('configForms') : ctx.configForms
  if (!slots || !forms) return

  // `settings.section` 是 root 级 list，由设置外壳声明；`slots.inject` 等它出现
  // 再注册，因此没装设置外壳的部署里这个页面不存在。
  const t = (key) => (activeLang(locale) === 'en' ? en : zh)[key]
  ctx.effect(
    () =>
      slots.inject('settings.section', () =>
        slots.register(
          {
            name: 'settings.section',
            id: SECTION_ID,
            order: SECTION_ORDER,
            label: () => t('nav'),
          },
          createPage(forms, locale),
        ),
      ),
    'web-fetch-fakeip: settings page',
  )
}

module.exports = { inject, apply }

    return module.exports;
  },
})
